(function () {
  'use strict';
  function t(key, params) { return window.I18n ? window.I18n.t(key, params) : key; }
  var KEY='glancemd-ultra-palette-recent', state={open:false,selected:0,recent:[]};
  function esc(s){return String(s).replace(/[&<>"']/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
  function runCommand(id,arg){if(window.Commands&&typeof window.Commands.run==='function')return window.Commands.run(id,arg);}
  function score(q,s){q=q.toLowerCase();s=s.toLowerCase();var i=0,n=0,last=-2;for(var c=0;c<q.length;c++){var p=s.indexOf(q[c],i);if(p<0)return -1;n+=1+(p===last+1?3:0);last=p;i=p+1;}return n;}
  function ensure(){var p=document.getElementById('command-palette');if(p)return p;p=document.createElement('section');p.id='command-palette';p.className='command-palette';p.hidden=true;p.innerHTML='<input id="palette-input" placeholder="' + t('palette.placeholder') + '"><div id="palette-list"></div>';document.body.appendChild(p);p.querySelector('input').oninput=render;if(p.addEventListener)p.addEventListener('keydown',function(e){if(!state.open)return;if(e.key==='Escape'){e.preventDefault();runCommand('palette.close');}else if(e.key==='ArrowDown'){e.preventDefault();runCommand('palette.selectNext');}else if(e.key==='ArrowUp'){e.preventDefault();runCommand('palette.selectPrevious');}else if(e.key==='Enter'){e.preventDefault();runCommand('palette.executeSelected');}});return p;}
  function definitions(){var ids=window.Commands&&Commands.ids?Commands.ids():[];return ids.map(function(id){return window.Commands.get?window.Commands.get(id):{id:id,label:id};}).filter(function(d){return d&&d.visibleInPalette!==false&&(!d.isEnabled||typeof d.isEnabled!=='function'||d.isEnabled())&&d.category!=='internal'&&d.category!=='Internal'&&String(d.id||'').indexOf('internal.')!==0;});}
  function currentItems(){var q=ensure().querySelector('input').value||'';return definitions().map(function(d){var text=[d.label,d.category,d.description,d.id].join(' ');return {d:d,s:score(q,text)};}).filter(function(x){return x.s>=0;}).sort(function(a,b){return b.s-a.s||a.d.label.localeCompare(b.d.label);});}
  function render(){var p=ensure(),items=currentItems();if(state.selected>=items.length)state.selected=Math.max(0,items.length-1);p.querySelector('#palette-list').innerHTML=items.map(function(x,i){return '<button class="palette-item '+(i===state.selected?'active':'')+'" data-id="'+esc(x.d.id)+'"><strong>'+esc(x.d.label)+'</strong><small>'+esc(x.d.category||'')+(x.d.description?' — '+esc(x.d.description):'')+'</small></button>';}).join('');Array.prototype.forEach.call(p.querySelectorAll('.palette-item'),function(b){b.onclick=function(){runCommand('palette.executeSelected');};});}
  function executeSelected(){var items=currentItems(),item=items[state.selected];if(!item)return;runCommand(item.d.id);state.recent.unshift(item.d.id);state.recent=state.recent.filter(function(x,i,a){return a.indexOf(x)===i;}).slice(0,5);try{localStorage.setItem(KEY,JSON.stringify(state.recent));}catch(e){}close();}
  function open(){state.open=true;var p=ensure();p.hidden=false;state.selected=0;p.querySelector('input').value='';p.querySelector('input').focus();render();}
  function close(){state.open=false;var p=document.getElementById('command-palette');if(p)p.hidden=true;}
  function toggle(){state.open?close():open();}
  function selectNext(){var items=currentItems();state.selected=Math.min(Math.max(0,items.length-1),state.selected+1);render();}
  function selectPrevious(){state.selected=Math.max(0,state.selected-1);render();}
  try{state.recent=JSON.parse(localStorage.getItem(KEY)||'[]')||[];}catch(e){}
  function registerCommands(){if(!window.Commands||typeof window.Commands.register!=='function')return;var reg=window.Commands.register;reg('palette.toggle',{label:'切换命令面板',category:'Navigation',run:toggle});reg('palette.open',{label:'打开命令面板',category:'Navigation',run:open});reg('palette.close',{label:'关闭命令面板',category:'Navigation',run:close});reg('palette.selectNext',{label:'命令面板下一项',category:'Navigation',run:selectNext});reg('palette.selectPrevious',{label:'命令面板上一项',category:'Navigation',run:selectPrevious});reg('palette.executeSelected',{label:'执行选中命令',category:'Navigation',run:executeSelected});}
  registerCommands();
  window.CommandPalette={open:open,close:close,toggle:toggle,selectNext:selectNext,selectPrevious:selectPrevious,executeSelected:executeSelected,run:function(id){runCommand(id);},score:score};
})();
