const { execFileSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { test, expect } = require('playwright/test');
const ROOT = path.resolve(__dirname, '..', '..', '..');
const PAGE = path.join(ROOT, 'tests', '.tmp', 'index.html');
function pageUrl(){execFileSync('python',[path.join(ROOT,'tools','build_test_page.py')],{cwd:ROOT,stdio:'pipe'});return pathToFileURL(PAGE).href;}
async function setup(page,value='a\nb\nc\n'){await page.goto(pageUrl());await page.click('#btn-new');const e=page.locator('#editor');await e.fill(value);await e.focus();return e;}

test('Eclipse Outline Ctrl+Shift+O 是 toggle 并恢复编辑器焦点',async({page})=>{const e=await setup(page,'# A\nbody');const p=page.locator('#panel-outline');await page.keyboard.press('Control+Shift+O');await expect(p).toHaveClass(/open/);await page.keyboard.press('Control+Shift+O');await expect(p).not.toHaveClass(/open/);await expect(e).toBeFocused();});
test('Eclipse Ctrl+Up/Down 仅滚动视口且光标不动',async({page})=>{const e=await setup(page,Array.from({length:80},(_,i)=>'line '+i).join('\n'));await e.evaluate(el=>{el.setSelectionRange(20,20);el.scrollTop=120;});const before=await e.evaluate(el=>({s:el.selectionStart,t:el.scrollTop}));await page.keyboard.press('Control+ArrowDown');const down=await e.evaluate(el=>({s:el.selectionStart,t:el.scrollTop}));expect(down.s).toBe(before.s);expect(down.t).toBeGreaterThan(before.t);await page.keyboard.press('Control+ArrowUp');expect((await e.evaluate(el=>el.selectionStart))).toBe(before.s);});
test('Eclipse Ctrl+Shift+Up/Down 在 Markdown 标题间导航',async({page})=>{const e=await setup(page,'# A\na\n## B\nb\nTitle C\n---\nc');await e.evaluate(el=>el.setSelectionRange(0,0));await page.keyboard.press('Control+Shift+ArrowDown');expect(await e.evaluate(el=>el.value.slice(0,el.selectionStart).split('\n').length)).toBe(3);await page.keyboard.press('Control+Shift+ArrowDown');expect(await e.evaluate(el=>el.value.slice(0,el.selectionStart).split('\n').length)).toBe(5);await page.keyboard.press('Control+Shift+ArrowUp');expect(await e.evaluate(el=>el.value.slice(0,el.selectionStart).split('\n').length)).toBe(3);});
test('Eclipse 行删除、撤销、重做',async({page})=>{const e=await setup(page);await e.evaluate(el=>el.setSelectionRange(2,2));await page.keyboard.press('Control+d');await expect(e).toHaveValue('a\nc\n');await page.keyboard.press('Control+z');await expect(e).toHaveValue('a\nb\nc\n');await page.keyboard.press('Control+y');await expect(e).toHaveValue('a\nc\n');});
test('Eclipse 行移动与复制',async({page})=>{const e=await setup(page);await e.evaluate(el=>el.setSelectionRange(2,3));await page.keyboard.press('Alt+ArrowUp');await expect(e).toHaveValue('b\na\nc\n');await page.keyboard.press('Control+Alt+ArrowDown');await expect(e).toHaveValue('b\nb\na\nc\n');});
test('Eclipse 大小写、HTML注释与反缩进',async({page})=>{const e=await setup(page,'    Hello');await e.evaluate(el=>el.setSelectionRange(4,9));await page.keyboard.press('Control+Shift+x');await expect(e).toHaveValue('    HELLO');await page.keyboard.press('Control+Shift+y');await expect(e).toHaveValue('    hello');await page.keyboard.press('Control+/');await expect(e).toHaveValue('    <!-- hello -->');await e.evaluate(el=>el.setSelectionRange(0,el.value.length));await page.keyboard.press('Shift+Tab');await expect(e).toHaveValue('<!-- hello -->');});
test('默认 Scheme 全部 commandId 在真实页面中已注册且无 pageerror',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(pageUrl());const missing=await page.evaluate(()=>Object.fromEntries(Object.entries(DefaultKeybindings.schemes).map(([id,rows])=>[id,rows.filter(r=>!Commands.has(r.commandId)).map(r=>r.commandId)])));expect(missing).toEqual({'ultra.eclipse':[],'ultra.vscode':[]});expect(errors).toEqual([]);});
