const path=require('node:path');const {pathToFileURL}=require('node:url');const {test,expect}=require('playwright/test');
const ROOT=path.resolve(__dirname,'..','..','..'),PAGE=path.join(ROOT,'tests','.tmp','index.html');function url(){return pathToFileURL(PAGE).href;}
test.beforeEach(async({page})=>{await page.goto(url());await page.evaluate(()=>{localStorage.clear();localStorage.setItem('glancemd-ultra-keyboard-scheme','ultra.vscode');if(window.Keybindings&&window.Keybindings.setScheme)window.Keybindings.setScheme('ultra.vscode');});await page.reload();});
test('VS Code 方案面板与导航键生效',async({page})=>{await page.keyboard.press('Control+Shift+p');await expect(page.locator('#command-palette')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('Control+Shift+f');await expect(page.locator('#search-panel')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('Control+p');await expect(page.locator('#quick-open')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('Control+Shift+o');await expect(page.locator('#panel-outline')).toHaveClass(/open/);await page.keyboard.press('Control+Shift+o');await expect(page.locator('#panel-outline')).not.toHaveClass(/open/);});
test('VS Code 文件、设置、Tab 与 F12 键生效',async({page})=>{await page.keyboard.press('Control+n');await page.keyboard.press('Control+n');await page.keyboard.press('Control+Tab');await expect(page.locator('#quick-open')).toBeVisible();expect(await page.evaluate(()=>QuickOpen.getState().mode)).toBe('tabs');await page.keyboard.press('Escape');await page.keyboard.press('Control+,');await expect(page.locator('#settings-panel')).toBeVisible();await page.keyboard.press('Escape');await page.locator('#btn-settings').focus();await page.keyboard.press('F12');await expect(page.locator('#editor')).toBeFocused();});
test('VS Code Ctrl+K Ctrl+S 打开快捷键设置',async({page})=>{await page.keyboard.press('Control+k');await page.keyboard.press('Control+s');await expect(page.locator('#settings-panel')).toBeVisible();await expect(page.locator('#settings-keybindings-mount')).toBeVisible();});
test('VS Code Ctrl+O、Ctrl+S、Ctrl+Shift+S、Ctrl+W 真实分派',async({page})=>{await page.keyboard.press('Control+o');let log=await page.evaluate(()=>__ipcLog.map(JSON.parse));expect(log.some(m=>m.command==='open_file')).toBeTruthy();await page.keyboard.press('Control+n');const e=page.locator('#editor');await e.fill('x');await e.focus();await page.keyboard.press('Control+s');await page.keyboard.press('Control+Shift+s');log=await page.evaluate(()=>__ipcLog.map(JSON.parse));expect(log.some(m=>m.command==='save_as'||m.command==='save_file')).toBeTruthy();// mock 环境补上真实 Rust 必回的 file_saved 回执（首次保存 requestId=1），使 markClean 生效、与真实保存链路一致
await page.evaluate(()=>window.__fromRust('file_saved',{path:'',requestId:1,tabId:TabManager.getState().activeTabId}));await page.keyboard.press('Control+w');// markDirty 为 300ms 防抖：若在保存分派后才触发，将弹出关闭确认，点击“放弃并关闭”兜底
const confirmBtn=page.locator('#confirm-dialog-btn-confirm');if(await confirmBtn.count())await confirmBtn.click();await expect(page.locator('.tab')).toHaveCount(0);});
