const path=require('node:path');const {pathToFileURL}=require('node:url');const {test,expect}=require('playwright/test');
const ROOT=path.resolve(__dirname,'..','..','..'),PAGE=path.join(ROOT,'tests','.tmp','index.html');function url(){return pathToFileURL(PAGE).href;}
test.beforeEach(async({page})=>{await page.goto(url());await page.evaluate(()=>{localStorage.clear();localStorage.setItem('glancemd-ultra-keyboard-scheme','ultra.vscode');if(window.Keybindings&&window.Keybindings.setScheme)window.Keybindings.setScheme('ultra.vscode');});await page.reload();});
test('VS Code 方案面板与导航键生效',async({page})=>{await page.keyboard.press('Control+Shift+p');await expect(page.locator('#command-palette')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('Control+Shift+f');await expect(page.locator('#search-panel')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('Control+p');await expect(page.locator('#quick-open')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('Control+Shift+o');await expect(page.locator('#panel-outline')).toHaveClass(/open/);await page.keyboard.press('Control+Shift+o');await expect(page.locator('#panel-outline')).not.toHaveClass(/open/);});
test('VS Code 文件、设置、Tab 与 F12 键生效',async({page})=>{await page.keyboard.press('Control+n');await page.keyboard.press('Control+n');await page.keyboard.press('Control+Tab');await expect(page.locator('#quick-open')).toBeVisible();expect(await page.evaluate(()=>QuickOpen.getState().mode)).toBe('tabs');await page.keyboard.press('Escape');await page.keyboard.press('Control+,');await expect(page.locator('#settings-panel')).toBeVisible();await page.keyboard.press('Escape');await page.locator('#btn-settings').focus();await page.keyboard.press('F12');await expect(page.locator('#editor')).toBeFocused();});
test('VS Code Ctrl+K Ctrl+S 打开快捷键设置',async({page})=>{await page.keyboard.press('Control+k');await page.keyboard.press('Control+s');await expect(page.locator('#settings-panel')).toBeVisible();await expect(page.locator('#settings-keybindings-mount')).toBeVisible();});
test('VS Code Ctrl+O、Ctrl+S、Ctrl+Shift+S、Ctrl+W 真实分派',async({page})=>{await page.keyboard.press('Control+o');let log=await page.evaluate(()=>__ipcLog.map(JSON.parse));expect(log.some(m=>m.command==='open_file')).toBeTruthy();await page.keyboard.press('Control+n');const e=page.locator('#editor');await e.fill('x');await e.focus();await page.keyboard.press('Control+s');await page.keyboard.press('Control+Shift+s');log=await page.evaluate(()=>__ipcLog.map(JSON.parse));expect(log.some(m=>m.command==='save_as')).toBeTruthy();const saveFile=log.filter(m=>m.command==='save_file').pop();expect(saveFile,'Ctrl+S 应分派 save_file').toBeTruthy();expect(saveFile.requestId).toBeGreaterThan(0);// 从 __ipcLog 捕获真实 save_file 的 requestId/tabId 回 file_saved（与真实 Rust 回执一致），不再硬编码 requestId
await page.evaluate(s=>window.__fromRust('file_saved',{path:'',requestId:s.requestId,tabId:s.tabId}),saveFile);expect(await page.evaluate(()=>TabManager.getActiveTab().dirty)).toBe(false);await page.keyboard.press('Control+w');// 保存已生效：直接关闭即通过；若保存链路失效（tab 仍 dirty）将弹确认且 tab 无法归零
await expect(page.locator('#confirm-dialog-btn-confirm')).toBeHidden();await expect(page.locator('.tab')).toHaveCount(0);});
